export const GET_NOTES_ACTION = 'GET_NOTES_ACTION';
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS';
export const GET_NOTES_ERROR = 'GET_NOTES_ERROR';
export const GET_NOTES_LOADING = 'GET_NOTES_LOADING';

export const ADD_NOTE_ACTION = 'ADD_NOTE_ACTION';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_ERROR = 'ADD_NOTE_ERROR';
export const ADD_NOTE_LOADING = 'ADD_NOTE_LOADING';

export const UPDATE_NOTE_ACTION = 'UPDATE_NOTE_ACTION';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_ERROR = 'UPDATE_NOTE_ERROR';
export const UPDATE_NOTE_LOADING = 'UPDATE_NOTE_LOADING';

export const ARCHIVE_NOTE_ACTION = 'ARCHIVE_NOTE_ACTION';
export const ARCHIVE_NOTE_SUCCESS = 'ARCHIVE_NOTE_SUCCESS';
export const ARCHIVE_NOTE_ERROR = 'ARCHIVE_NOTE_ERROR';
export const ARCHIVE_NOTE_LOADING = 'ARCHIVE_NOTE_LOADING';

export const DELETE_NOTE_ACTION = 'DELETE_NOTE_ACTION';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_ERROR = 'DELETE_NOTE_ERROR';
export const DELETE_NOTE_LOADING = 'DELETE_NOTE_LOADING';

export const CALL_PENDING_SUBMITS_ACTION = 'CALL_PENDING_SUBMITS_ACTION';
export const CALL_PENDING_SUBMITS_SUCCESS = 'CALL_PENDING_SUBMITS_SUCCESS';
export const CALL_PENDING_SUBMITS_ERROR = 'CALL_PENDING_SUBMITS_ERROR';
export const CALL_PENDING_SUBMITS_LOADING = 'CALL_PENDING_SUBMITS_LOADING';

export const ADD_PENDING_NOTE = 'ADD_PENDING_NOTE';
export const UPDATE_PENDING_NOTE = 'UPDATE_PENDING_NOTE';
export const ARCHIVE_PENDING_NOTE = 'ARCHIVE_PENDING_NOTE';
export const DELETE_PENDING_NOTE = 'DELETE_PENDING_NOTE';

export const SET_PENDING_DATA = 'SET_PENDING_DATA';

export const CLEAR_ERROR = 'CLEAR_ERROR';
