export const GET_NOTES_ACTION = 'GET_NOTES_ACTION';
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS';
export const GET_NOTES_ERROR = 'GET_NOTES_ERROR';
export const GET_NOTES_LOADING = 'GET_NOTES_LOADING';

export const ADD_PENDING_NOTE = 'ADD_PENDING_NOTE';
export const UPDATE_PENDING_NOTE = 'UPDATE_PENDING_NOTE';

export const CLEAR_ERROR = 'CLEAR_ERROR';
