export const ADD_NOTE_ACTION = 'ADD_NOTE_ACTION';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_ERROR = 'ADD_NOTE_ERROR';
export const ADD_NOTE_LOADING = 'ADD_NOTE_LOADING';

export const UPDATE_NOTE_ACTION = 'UPDATE_NOTE_ACTION';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_ERROR = 'UPDATE_NOTE_ERROR';
export const UPDATE_NOTE_LOADING = 'UPDATE_NOTE_LOADING';

export const CLEAR_ERROR = 'CLEAR_ERROR';
